version: "3"
services:
  callback_receiver:
    container_name: "callback_receiver"
    build: ./callback_receiver
    # $HTTP_PORT is user-defined in tetris.env
    ports:
      - $HTTP_PORT:$HTTP_PORT
    volumes:
      - ./callback_receiver:/code
    environment:
      - HTTP_PORT=$HTTP_PORT
      - BACKEND_PORT=$GO_PORT
      - BACKEND_URL=backend_server
    command: python -u -m server.server
  backend:
    container_name: "backend_server"
    build: ./backend
    # $GO_PORT is user-defined in tetris.env
    ports:
      - $GO_PORT:$GO_PORT
    environment:
      - GO_PORT=$GO_PORT
    command: ./goBackend
  frontend:
    container_name: "frontend_server"
    build: ./frontend
    # $REACT_PORT is user-defined in tetris.env
    ports:
      - $REACT_PORT:$REACT_PORT
    volumes:
      - ./frontend:/code
    environment:
      - PORT=$REACT_PORT
      - REACT_APP_BACKEND_PORT=$GO_PORT
      - REACT_APP_BACKEND_URL=localhost
