version: "1"
services:
  callback_receiver:
    container_name: "callback_receiver"
    build: ./callback_receiver
    # $HTTP_PORT is user-defined in tetris.env
    ports:
      - $HTTP_PORT:$HTTP_PORT
    volumes:
      - ./callback_receiver:/code
      - HTTP_PORT=$HTTP_PORT
    command: python -u -m server.server
  backend:
    container_name: "backend_server"
    build: ./backend
    # $GO_PORT is user-defined in tetris.env
    ports:
      - $GO_PORT:$GO_PORT
    environment:
      - GO_PORT=$GO_PORT
  frontend:
    container_name: "frontend_server"
    build: ./tetris_react
    # $REACT_PORT is user-defined in tetris.env
    ports:
      - $REACT_PORT:$REACT_PORT
    volumes:
      - ./tetris_react:/code
    environment:
      - REACT_PORT=$REACT_PORT
    command: npm start
