version: "3"
services:
  callback_receiver:
    container_name: "callback_receiver"
    build: .
    ports:
      - $HTTP_PORT:$HTTP_PORT
    volumes:
      - .:/code
    environment:
      - HTTP_PORT=$HTTP_PORT
    command: python -u -m server.server

