const numberInputParams = [
    ["seuil_min_ana30v", 0, 30, .25, "V", "Seuil min tension analogique 30V"],
    ["activ_min_ana30v", 0, 1, 1, "", "Activation seuil min tension analogique 30V"],
    ["seuil_max_ana30v", 0, 30, .25, "V", "Seuil max tension analogique 30V"],
    ["activ_max_ana30v", 0, 1, 1, "", "Activation seuil max tension analogique 30V"],
    ["seuil_min_ana100mv", -100, 100, 1, "mV", "Seuil min tension analogique 100mV"],
    ["seuil_max_ana100mv", -100, 100, 1, "mV", "Seuil max tension analogique 100mV"],
    ["duree_cycle_feux", 1, 32, 1, "s", "Durée de cycles de feux"],
    ["acq_position_base", 0, 1, 1, "", "Acquisition position"],
    ["activ_min_ana100mv", 0, 1, 1, "", "Activation seuil min tension analogique 100mV"],
    ["activ_max_ana100mv", 0, 1, 1, "", "Activation seuil max tension analogique 100mV"],
    ["active_tor1", 0, 1, 1, "", "Alarme inactive/active TOR 1"],
    ["active_tor2", 0, 1, 1, "", "Alarme inactive/active TOR 2"],
    ["active_tor3", 0, 1, 1, "", "Alarme inactive/active TOR 3"],
    ["active_tor4", 0, 1, 1, "", "Alarme inactive/active TOR 4"],
    ["active_tor5", 0, 1, 1, "", "Alarme inactive/active TOR 5"],
    ["active_tor6", 0, 1, 1, "", "Alarme inactive/active TOR 6"],
    ["sens_tor1", 0, 1, 1, "","Sens entrée TOR 1"],
    ["sens_tor2", 0, 1, 1, "","Sens entrée TOR 2"],
    ["sens_tor3", 0, 1, 1, "","Sens entrée TOR 3"],
    ["sens_tor4", 0, 1, 1, "","Sens entrée TOR 4"],
    ["sens_tor5", 0, 1, 1, "","Sens entrée TOR 5"],
    ["sens_tor6", 0, 1, 1, "","Sens entrée TOR 6"],
    ["delai_envoi", 0, 7, 1, "", "Délai envoi auto"],
    ["delai_repet", 0, 1, 1, "", "Délai répétition alerte"],
    ["r_deradage", 0, 31, 1, "", "Rayon déradage"],
    ["sommeil", 0, 1, 1, "", "Mode sommeil"],
    ["switch_config", 0, 1, 1, "", "Config switch"],
]
export default numberInputParams